{% set name = "django-mptt" %}
{% set version = "0.9.1" %}
{% set sha256 = "689a04cce0981671d6061a9928c33a16b47abb0d4cd43cf7dec31ae284fdae9d" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - python
    - pip
  run:
    - python
    - django-js-asset
    - django >=1.8

test:
  imports:
    - mptt
    - mptt.templatetags

about:
  home: https://github.com/django-mptt/django-mptt
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'Utilities for implementing a modified pre-order traversal tree in django.'
  description: 
    Utilities for implementing Modified Preorder Tree Traversal with your Django Models 
    and working with trees of Model instances.
  doc_url: https://django-mptt.readthedocs.io/
  dev_url: https://github.com/django-mptt/django-mptt

extra:
  recipe-maintainers:
    - cshaley
    - sannykr
