{% set name = "django-mptt" %}
{% set version = "0.12.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/django-mptt-{{ version }}.tar.gz
  sha256: 8ae6c3821127b529bb2f938de27bf0771b1bcbe9dbccdfba33986af78611f13a

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.5
  run:
    - django >=1.11
    - django-js-asset
    - python >=3.5

test:
  imports:
    - mptt
    - mptt.templatetags
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/django-mptt/django-mptt
  summary: Utilities for implementing Modified Preorder Tree Traversal with your Django Models and working with trees of Model instances.
  license: MIT
  license_family: MIT
  license_file: LICENSE
  description: Utilities for implementing Modified Preorder Tree Traversal with your Django Models and working with trees of Model instances.
  doc_url: https://django-mptt.readthedocs.io/
  dev_url: https://github.com/django-mptt/django-mptt

extra:
  recipe-maintainers:
    - cshaley
    - sannykr
    - hadim
