travis:
  secure:
    BINSTAR_TOKEN: jfs/1jrf9rD5l+Blc8KryYIyivsHAam3UXv7F830J59qQMMXrGZvLVw8LteX+R36AU7S+aoO+n16tOdDEzKS/caDEbDu98yniFC9MKrxZwHWTRE9jalkUBaVvvIo0IPr3Thmwrd7dv367KQrgsiqlPh8LdtJjj37KK8v0NtzDGAmSROJzsSazGvAaHggTZFPNl13V1No2E+BPuPskdke2Y7c+SsNmz8b6aXZPV8Lv/CIKVF5ohrgSv2LsbUqOKS+tvfzBkwGILnga+hJFJDsokN+w3zWlgJkY+pPDt5ufJF9dXN9WVmNJcDCEqG51jvtL6MqzJlST6FePJGIsnl4yAUvcWVDs6i+2nKh2bkWMrkjpZkxyLSQCrC1OE70LCzmaDgyQg5lN8FCI4lhZjv64TmUQLf+13xBiO9jq9n1kbzlgSIJ98gPdhKPmYoGzXSbT4s//WUC5M6CD+e7no76GqnPg1xpGN4d4nz20gQI4YRq/ANH9LUpRppDzkt5GRqV1v2POESXpm9JFOgS9u8iix1MJhC4Ux4qo4hQl9Cw7jt1GnZjxLDCsaFj8ia0a8QFHMDSGB44I2ZBjGP6o9Y01Ygilm8M96efYVa7tclGiFfgD93s6tlCNuzWS74R4Qf3EnbKJPu5lVlaHkss3iw1HTEjr1kS0X5u14NUtL/nB+s=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
