travis:
  secure:
    BINSTAR_TOKEN: YsPBkeTfKGyqEAntXGg5CLtv6GTMvJbKyhtIVRHD8d6Bv7AEzkgDjqZ/vjxJn0zpp61OiAEUWTwo6kpgqLU6H/nm8GKXPU2j1B+0cN4NaTNzHJ2ULZMJ3cG9b3HzciJztgNu7IHg03E3eIWQj+B7U8OVkjugQxOltVIH/dOsVr/b5eaHKiKgsMcoRye/3PdxXjpSUISSyFPo+zfYAFRKVMk87JQX9D/+rtvwEI/2p57i2Zs1zVTIDh5inAinEny0/nj0bDxweQPPJ6bBIBtOosPqQU6IUU7zYBWT5xCgKXEbDJpdFD4qnkbM9QDugMzZoHRiheYIRFCt8m2lDsIzhlzWm53r3B36AvNppKicUwATVW5IX8FCgRDnpj1MUjCNllnuclxOqsVR6h3eCl5UtUFOkEuR/IGverVN+H22jNHbgDGhuFZ7vOTuWTyUoMvh8JI3/sVi5WuOJALMXvmSY1TwvFIimCTbB2AiGP6mhg7eflhDsogQXngawwhZrqLtQlLS7+VWc18Z9/MQxYc3uLdja2S4srkHvfs5g+DZB4OrM4KKMC4zStCe6S01e+Q0QaJ33SUwnA3w9W9qdaiMQVnxeFuS/mP2ffWOp4p8jsuSUmwVIeofXDph39pZkC4VVLgDtgxd+GUBw9tGkIFsX7cBWosC/tW8y2Jms95jQ5M=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
